server:
  port: 8080
  servlet:
    contextPath: /onlineshopping
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:~/onlineshopping;AUTO_SERVER=TRUE
    username: root
    password: 123456
    driverClassName: org.h2.Driver
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    platform: h2
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2
      enabled: true
